<a href="https://colab.research.google.com/github/jeos54951/homework/blob/master/%EC%97%B4%EC%9C%A0%EC%B2%B4%EA%B3%B5%ED%95%99%EC%8B%A4%ED%97%98-2015011294-HW04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import math
import numpy as np
from numba import jit,vectorize, cuda
import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-10.0/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so"
a= int(input("input a:"))
def function(a):
  for b in range(1,10):
    print(a,"x",b,"=",a*b,"입니다.")

  return a
      
  
print('NORMAL')
function(int(a))
print()
  


def gama(a):
  x1 = np.arange(1,10)
  x2 = x1*a
  x1 = x2.reshape((9,1))

  return x1

print('NUMPY')
print(gama(a))
print()

@jit(nopython=True)
def alpha(a):
  x3 = np.arange(1,10)
  x4 = x3*a
  x3 = x4.reshape((9,1))
  print(x3)
  return x3
print('NUMBA JIT')
alpha(int(a))
print()


@vectorize(['int64(int64,int64)'],target='cuda')
def beta(y,z):
  return y*z


x7 = np.arange(1,10)
D = beta(a,x7).reshape((9,1))

print('CUDA')
print(D)
print()

print("Normal Compiling Time(s) : ", end = "")
%timeit function

print("Numpy Compiling Time(s) : ", end = "")
%timeit gama

print("Numba Jit Compiling Time(s) : ", end = "")
%timeit alpha

print("Cuda Compiling Time(s) : ", end = "")
%timeit beta

input a:1
NORMAL
1 x 1 = 1 입니다.
1 x 2 = 2 입니다.
1 x 3 = 3 입니다.
1 x 4 = 4 입니다.
1 x 5 = 5 입니다.
1 x 6 = 6 입니다.
1 x 7 = 7 입니다.
1 x 8 = 8 입니다.
1 x 9 = 9 입니다.

NUMPY
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

NUMBA JIT
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

CUDA
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Normal Compiling Time(s) : 100000000 loops, best of 3: 18.1 ns per loop
Numpy Compiling Time(s) : 10000000 loops, best of 3: 21.7 ns per loop
Numba Jit Compiling Time(s) : 100000000 loops, best of 3: 18.1 ns per loop
Cuda Compiling Time(s) : 10000000 loops, best of 3: 19.6 ns per loop
